# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{org-parse}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["knb"]
  s.date = %q{2010-03-09}
  s.default_executable = %q{org-parse}
  s.description = %q{This gem contains libraries for parsing org-mode files and build other format file}
  s.email = %q{knb@artif.org}
  s.executables = ["org-parse"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "bin/org-parse",
     "lib/org-parse.rb",
     "lib/org-parse/inline-parser.output",
     "lib/org-parse/inline-parser.rb",
     "lib/org-parse/inline-parser.ry",
     "lib/org-parse/inline-parser.tab.rb",
     "lib/org-parse/node.rb",
     "lib/org-parse/struct-parser.output",
     "lib/org-parse/struct-parser.rb",
     "lib/org-parse/struct-parser.ry",
     "lib/org-parse/struct-parser.tab.rb",
     "lib/org-parse/struct-scanner.rb",
     "lib/org-parse/templates/single.html.erb",
     "lib/org-parse/utils.rb",
     "lib/org-parse/visitor.rb",
     "rakelib/racc.rake",
     "test/data/blocks.org",
     "test/data/emphasis.org",
     "test/data/footnote.html",
     "test/data/footnote.org",
     "test/data/html-export.html",
     "test/data/html-export.org",
     "test/data/images.org",
     "test/data/index.org",
     "test/data/lily20100228.jpg",
     "test/data/lily20100228t.jpg",
     "test/data/link.org",
     "test/data/list_before_1st_headline.html",
     "test/data/list_before_1st_headline.org",
     "test/data/lists.html",
     "test/data/lists.org",
     "test/data/no-headline.org",
     "test/data/one-headline.org",
     "test/data/paragraph.org",
     "test/data/quote.org",
     "test/data/sections.html",
     "test/data/sections.org",
     "test/data/simple-list.org",
     "test/data/skip_t.org",
     "test/data/structure.org",
     "test/data/table.org",
     "test/data/test-list.org",
     "test/data/text-bef-hl.org",
     "test/data/text.org",
     "test/data/title.html",
     "test/data/title.org",
     "test/data/verse.org",
     "test/helper.rb",
     "test/test_org-parse.rb",
     "tmp/footnote.html",
     "tmp/html-export.html",
     "tmp/lily20100228.jpg",
     "tmp/lily20100228t.jpg",
     "tmp/lists.html"
  ]
  s.homepage = %q{http://github.com/knb/org-parse}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{parse and convert Org-Mode file}
  s.test_files = [
    "test/test_org-parse.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

