#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "lib/org-parse/inline-parser.ry".
#

require 'racc/parser'


module OrgParse

  class InlineParser < Racc::Parser

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 1, 23, :_reduce_none,
 2, 24, :_reduce_2,
 1, 24, :_reduce_3,
 1, 25, :_reduce_none,
 1, 25, :_reduce_none,
 1, 25, :_reduce_none,
 1, 25, :_reduce_none,
 1, 25, :_reduce_none,
 1, 25, :_reduce_none,
 1, 25, :_reduce_none,
 1, 25, :_reduce_none,
 1, 25, :_reduce_none,
 3, 26, :_reduce_13,
 3, 27, :_reduce_14,
 3, 28, :_reduce_15,
 3, 29, :_reduce_16,
 3, 31, :_reduce_17,
 3, 30, :_reduce_18,
 2, 35, :_reduce_19,
 1, 35, :_reduce_none,
 1, 34, :_reduce_21,
 1, 32, :_reduce_22,
 2, 36, :_reduce_23,
 1, 36, :_reduce_24,
 1, 37, :_reduce_none,
 1, 37, :_reduce_none,
 1, 37, :_reduce_none,
 1, 37, :_reduce_none,
 1, 37, :_reduce_none,
 3, 33, :_reduce_30,
 1, 33, :_reduce_31 ]

racc_reduce_n = 32

racc_shift_n = 49

racc_action_table = [
     8,    25,    12,     8,    16,    12,    20,    22,    40,     2,
     6,    25,    10,     6,    14,    10,    18,    47,     8,    18,
    12,    24,    16,   nil,    20,    22,   nil,     2,     6,     8,
    10,    12,    14,    16,    18,    20,    22,   nil,     2,     6,
     8,    10,    12,    14,    16,    18,    20,    22,   nil,     2,
     6,     8,    10,    12,    14,    16,    18,    20,    22,   nil,
     2,     6,     8,    10,    12,    14,    16,    18,    20,    22,
   nil,     2,     6,     8,    10,    12,    14,    16,    18,    20,
    22,   nil,     2,     6,     8,    10,    12,    14,    16,    18,
    20,    22,    48,     2,     6,     8,    10,    12,    14,    16,
    18,    20,    22,   nil,     2,     6,     8,    10,    12,    14,
    16,    18,    20,    22,   nil,     2,     6,   nil,    10,   nil,
    14,    44,    18,     8,   nil,    12,   nil,   nil,    46,   nil,
   nil,   nil,   nil,     6,     8,    10,    12,   nil,    16,    18,
    20,    22,   nil,     2,     6,    41,    10,     8,    14,    12,
    18,    16,   nil,    20,    22,   nil,     2,     6,   nil,    10,
    42,    14,     8,    18,    12,    43,    16,   nil,    20,    22,
   nil,     2,     6,     8,    10,    12,    14,    16,    18,    20,
    22,   nil,     2,     6,   nil,    10,   nil,    14,   nil,    18 ]

racc_action_check = [
    38,    31,    38,    16,    38,    16,    38,    38,    24,    38,
    38,     5,    38,    16,    38,    16,    38,    38,    14,    16,
    14,     4,    14,   nil,    14,    14,   nil,    14,    14,     0,
    14,     0,    14,     0,    14,     0,     0,   nil,     0,     0,
     6,     0,     6,     0,     6,     0,     6,     6,   nil,     6,
     6,     7,     6,     7,     6,     7,     6,     7,     7,   nil,
     7,     7,    10,     7,    10,     7,    10,     7,    10,    10,
   nil,    10,    10,    12,    10,    12,    10,    12,    10,    12,
    12,   nil,    12,    12,    39,    12,    39,    12,    39,    12,
    39,    39,    39,    39,    39,    18,    39,    18,    39,    18,
    39,    18,    18,   nil,    18,    18,    30,    18,    30,    18,
    30,    18,    30,    30,   nil,    30,    30,   nil,    30,   nil,
    30,    30,    30,    32,   nil,    32,   nil,   nil,    32,   nil,
   nil,   nil,   nil,    32,    26,    32,    26,   nil,    26,    32,
    26,    26,   nil,    26,    26,    26,    26,    28,    26,    28,
    26,    28,   nil,    28,    28,   nil,    28,    28,   nil,    28,
    28,    28,    29,    28,    29,    29,    29,   nil,    29,    29,
   nil,    29,    29,    22,    29,    22,    29,    22,    29,    22,
    22,   nil,    22,    22,   nil,    22,   nil,    22,   nil,    22 ]

racc_action_pointer = [
    26,   nil,   nil,   nil,    21,     8,    37,    48,   nil,   nil,
    59,   nil,    70,   nil,    15,   nil,     0,   nil,    92,   nil,
   nil,   nil,   170,   nil,     8,   nil,   131,   nil,   144,   159,
   103,    -2,   120,   nil,   nil,   nil,   nil,   nil,    -3,    81,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
   -32,   -11,   -21,   -12,   -32,   -22,   -32,    -1,   -20,    -3,
   -32,    -4,   -32,    -5,   -32,    -6,   -32,    -7,   -32,    -8,
   -31,    -9,   -32,   -10,   -32,   -19,   -32,    -2,   -32,   -32,
   -32,   -29,   -32,   -25,   -24,   -26,   -27,   -28,   -32,   -32,
    49,   -14,   -15,   -13,   -17,   -23,   -30,   -16,   -18 ]

racc_goto_table = [
    27,    33,     7,    32,     4,   nil,   nil,   nil,    26,    34,
    35,    31,    28,    37,    29,   nil,    30,    33,    36,    27,
    38,    27,    27,    27,    39,    45,    35,    31,   nil,    37,
   nil,    27,    27,   nil,    36 ]

racc_goto_check = [
     3,     4,     2,    14,     1,   nil,   nil,   nil,     2,    15,
     5,    13,     2,     7,     2,   nil,     2,     4,     6,     3,
     2,     3,     3,     3,     2,    15,     5,    13,   nil,     7,
   nil,     3,     3,   nil,     6 ]

racc_goto_pointer = [
   nil,     4,     2,    -7,   -15,    -6,     2,    -3,   nil,   nil,
   nil,   nil,   nil,    -5,   -13,    -7 ]

racc_goto_default = [
   nil,   nil,   nil,     9,    11,    13,    15,    17,    19,    21,
    23,     1,     3,     5,   nil,   nil ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :EX_LOW => 2,
 :OTHER => 3,
 :EX_HIGH => 4,
 :EM_OPEN => 5,
 :EM_CLOSE => 6,
 :LINK_START => 7,
 :LINK_END => 8,
 :LINK_URI => 9,
 :ST_OPEN => 10,
 :ST_CLOSE => 11,
 :QUOTE => 12,
 :IT_OPEN => 13,
 :IT_CLOSE => 14,
 :UL_OPEN => 15,
 :UL_CLOSE => 16,
 :VERB_OPEN => 17,
 :VERB_CLOSE => 18,
 :CODE_OPEN => 19,
 :CODE_CLOSE => 20,
 :EOL => 21 }

racc_use_result_var = true

racc_nt_base = 22

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'EX_LOW',
'OTHER',
'EX_HIGH',
'EM_OPEN',
'EM_CLOSE',
'LINK_START',
'LINK_END',
'LINK_URI',
'ST_OPEN',
'ST_CLOSE',
'QUOTE',
'IT_OPEN',
'IT_CLOSE',
'UL_OPEN',
'UL_CLOSE',
'VERB_OPEN',
'VERB_CLOSE',
'CODE_OPEN',
'CODE_CLOSE',
'EOL',
'$start',
'content',
'elements',
'element',
'emphasis',
'italic',
'under_line',
'code',
'strike',
'verb',
'normal_string_element',
'link',
'quote',
'normal_strings',
'link_descs',
'link_desc']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

 # reduce 1 omitted

module_eval <<'.,.,', 'lib/org-parse/inline-parser.ry', 18
  def _reduce_2( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/inline-parser.ry', 19
  def _reduce_3( val, _values, result )
 result = val
   result
  end
.,.,

 # reduce 4 omitted

 # reduce 5 omitted

 # reduce 6 omitted

 # reduce 7 omitted

 # reduce 8 omitted

 # reduce 9 omitted

 # reduce 10 omitted

 # reduce 11 omitted

 # reduce 12 omitted

module_eval <<'.,.,', 'lib/org-parse/inline-parser.ry', 32
  def _reduce_13( val, _values, result )
 result = Node.new(:EMPHASIS, val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/inline-parser.ry', 35
  def _reduce_14( val, _values, result )
 result = Node.new(:ITALIC, val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/inline-parser.ry', 38
  def _reduce_15( val, _values, result )
 result = Node.new(:UNDER_LINE, val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/inline-parser.ry', 41
  def _reduce_16( val, _values, result )
 result = Node.new(:CODE, val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/inline-parser.ry', 44
  def _reduce_17( val, _values, result )
 result = Node.new(:VERBATIM, val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/inline-parser.ry', 47
  def _reduce_18( val, _values, result )
 result = Node.new(:STRIKE_THROUGH, val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/inline-parser.ry', 49
  def _reduce_19( val, _values, result )
 result << val[1]
   result
  end
.,.,

 # reduce 20 omitted

module_eval <<'.,.,', 'lib/org-parse/inline-parser.ry', 52
  def _reduce_21( val, _values, result )
 result = Node.new(:QUOTE, [], val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/inline-parser.ry', 55
  def _reduce_22( val, _values, result )
 result = Node.new(:STRING, [], val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/inline-parser.ry', 57
  def _reduce_23( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/inline-parser.ry', 58
  def _reduce_24( val, _values, result )
 result = val
   result
  end
.,.,

 # reduce 25 omitted

 # reduce 26 omitted

 # reduce 27 omitted

 # reduce 28 omitted

 # reduce 29 omitted

module_eval <<'.,.,', 'lib/org-parse/inline-parser.ry', 66
  def _reduce_30( val, _values, result )
 result = LinkNode.new(val[0], val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/inline-parser.ry', 67
  def _reduce_31( val, _values, result )
 result = LinkNode.new(val[0])
   result
  end
.,.,

 def _reduce_none( val, _values, result )
  result
 end

  end   # class InlineParser

end   # module OrgParse
