#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "lib/org-parse/struct-parser.ry".
#

require 'racc/parser'


module OrgParse

  class StructParser < Racc::Parser

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 1, 25, :_reduce_none,
 2, 25, :_reduce_2,
 2, 26, :_reduce_3,
 1, 26, :_reduce_none,
 1, 28, :_reduce_5,
 2, 27, :_reduce_6,
 1, 27, :_reduce_7,
 2, 30, :_reduce_8,
 1, 31, :_reduce_9,
 2, 31, :_reduce_10,
 1, 32, :_reduce_11,
 2, 33, :_reduce_12,
 1, 33, :_reduce_13,
 1, 34, :_reduce_none,
 1, 34, :_reduce_none,
 1, 34, :_reduce_none,
 1, 34, :_reduce_none,
 1, 34, :_reduce_none,
 1, 34, :_reduce_none,
 1, 34, :_reduce_none,
 2, 29, :_reduce_21,
 1, 29, :_reduce_22,
 1, 41, :_reduce_none,
 1, 41, :_reduce_none,
 1, 41, :_reduce_none,
 1, 41, :_reduce_none,
 1, 41, :_reduce_none,
 1, 41, :_reduce_none,
 1, 40, :_reduce_29,
 2, 39, :_reduce_30,
 1, 39, :_reduce_31,
 2, 35, :_reduce_32,
 1, 35, :_reduce_33,
 1, 42, :_reduce_34,
 1, 42, :_reduce_none,
 1, 43, :_reduce_36,
 1, 38, :_reduce_none,
 1, 38, :_reduce_none,
 1, 38, :_reduce_none,
 3, 36, :_reduce_40,
 1, 36, :_reduce_41,
 2, 47, :_reduce_42,
 1, 47, :_reduce_43,
 1, 48, :_reduce_44,
 3, 44, :_reduce_45,
 3, 45, :_reduce_46,
 3, 46, :_reduce_47,
 2, 49, :_reduce_48,
 1, 49, :_reduce_49,
 3, 50, :_reduce_50,
 2, 50, :_reduce_51,
 3, 37, :_reduce_52,
 1, 37, :_reduce_53,
 2, 51, :_reduce_54,
 1, 51, :_reduce_55,
 1, 52, :_reduce_56,
 1, 53, :_reduce_57 ]

racc_reduce_n = 58

racc_shift_n = 73

racc_action_table = [
    18,    22,    24,    65,    29,     4,    35,    69,    55,    13,
    55,    17,    20,    18,    26,    57,    32,    29,    55,    72,
    18,    22,    24,    18,    29,    55,    35,    29,    55,    13,
    57,    17,    20,    35,    26,    40,    32,    71,    55,    67,
    18,    22,    24,     6,    29,    38,    35,    24,    58,    13,
    24,    17,    20,     6,    26,     5,    32,    18,    22,    24,
    24,    29,   nil,    35,   nil,     6,    13,   nil,    17,    20,
   nil,    26,   nil,    32,    18,    22,    24,   nil,    29,   nil,
    35,   nil,   nil,    13,   nil,    17,    20,   nil,    26,   nil,
    32,    18,    22,    24,   nil,    29,   nil,    35,   nil,   nil,
    13,   nil,    17,    20,   nil,    26,   nil,    32,    18,    22,
    24,   nil,    29,    64,    35,   nil,   nil,    13,   nil,    17,
    20,   nil,    26,   nil,    32,    18,    22,    24,   nil,    29,
   nil,    35,   nil,     6,    13,   nil,    17,    20,   nil,    26,
   nil,    32 ]

racc_action_check = [
    68,    68,    68,    53,    68,     0,    68,    56,    53,    68,
    56,    68,    68,    15,    68,    27,    68,    15,    32,    68,
    55,    55,    55,    43,    55,    26,    55,    43,    20,    55,
    47,    55,    55,    16,    55,     9,    55,    62,    62,    55,
     3,     3,     3,     7,     3,     5,     3,    28,    28,     3,
    59,     3,     3,     2,     3,     1,     3,    41,    41,    41,
    70,    41,   nil,    41,   nil,    41,    41,   nil,    41,    41,
   nil,    41,   nil,    41,    17,    17,    17,   nil,    17,   nil,
    17,   nil,   nil,    17,   nil,    17,    17,   nil,    17,   nil,
    17,    31,    31,    31,   nil,    31,   nil,    31,   nil,   nil,
    31,   nil,    31,    31,   nil,    31,   nil,    31,    52,    52,
    52,   nil,    52,    52,    52,   nil,   nil,    52,   nil,    52,
    52,   nil,    52,   nil,    52,    10,    10,    10,   nil,    10,
   nil,    10,   nil,    10,    10,   nil,    10,    10,   nil,    10,
   nil,    10 ]

racc_action_pointer = [
    -5,    55,    42,    37,   nil,    45,   nil,    32,   nil,    22,
   122,   nil,   nil,   nil,   nil,    10,    24,    71,   nil,   nil,
     7,   nil,   nil,   nil,   nil,   nil,     4,    11,    42,   nil,
   nil,    88,    -3,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    54,   nil,    20,   nil,   nil,   nil,    26,   nil,   nil,
   nil,   nil,   105,   -13,   nil,    17,   -11,   nil,   nil,    45,
   nil,   nil,    17,   nil,   nil,   nil,   nil,   nil,    -3,   nil,
    55,   nil,   nil ]

racc_action_default = [
   -58,   -58,    -1,    -4,    -5,   -58,   -11,    -2,    -7,   -58,
    -9,   -37,   -38,   -29,   -39,   -23,   -41,   -58,   -34,   -24,
   -58,   -43,   -31,   -25,   -57,   -26,   -58,   -27,   -53,   -36,
   -28,    -3,   -58,   -22,   -55,   -44,   -33,   -35,    73,    -6,
    -8,   -10,   -13,   -15,   -16,   -17,   -18,   -19,   -20,   -14,
   -32,   -42,   -58,   -58,   -49,   -58,   -58,   -30,   -56,   -58,
   -54,   -21,   -58,   -12,   -40,   -45,   -48,   -51,   -58,   -46,
   -52,   -47,   -50 ]

racc_goto_table = [
    31,    60,    61,    44,    48,    47,    45,    42,    66,    43,
    46,    66,    53,    51,    52,     8,    50,    66,    56,     7,
    39,     2,     3,    61,    62,    41,    70,    59,     1,   nil,
   nil,   nil,   nil,   nil,    44,    48,    47,    45,    63,    61,
    43,    46,   nil,    60,    50,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    68 ]

racc_goto_check = [
     5,    29,    17,    12,    16,    15,    13,    10,    26,    11,
    14,    26,    25,    24,     5,     6,    18,    26,    25,     3,
     6,     2,     4,    17,    25,     9,    27,    28,     1,   nil,
   nil,   nil,   nil,   nil,    12,    16,    15,    13,    10,    17,
    11,    14,   nil,    29,    18,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     5 ]

racc_goto_pointer = [
   nil,    28,    21,    17,    22,    -3,    13,   nil,   nil,    15,
    -3,    -1,    -7,    -4,     0,    -5,    -6,   -29,     1,   nil,
   nil,   nil,   nil,   nil,    -3,    -8,   -45,   -33,    -1,   -27 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,    49,     9,    10,   nil,
   nil,    15,    19,    23,    25,    27,    30,    33,    36,    37,
    11,    12,    14,    16,    21,   nil,    54,    28,   nil,    34 ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :PLOW => 2,
 :TEXTLINE => 3,
 :WHITELINE => 4,
 :TABLE_ROW => 5,
 :TABLE_SEP => 6,
 :QUOTE => 7,
 :BLOCK_END => 8,
 :EXAMPLE => 9,
 :DOCUMENT_START => 10,
 :HEADLINE => 11,
 :VARIABLELINE => 12,
 :SEC_END => 13,
 :BLOCK_START => 14,
 :UL_START => 15,
 :UL_END => 16,
 :OL_START => 17,
 :OL_END => 18,
 :DL_START => 19,
 :DL_END => 20,
 :LI_START => 21,
 :LI_END => 22,
 :P_END => 23 }

racc_use_result_var = true

racc_nt_base = 24

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'PLOW',
'TEXTLINE',
'WHITELINE',
'TABLE_ROW',
'TABLE_SEP',
'QUOTE',
'BLOCK_END',
'EXAMPLE',
'DOCUMENT_START',
'HEADLINE',
'VARIABLELINE',
'SEC_END',
'BLOCK_START',
'UL_START',
'UL_END',
'OL_START',
'OL_END',
'DL_START',
'DL_END',
'LI_START',
'LI_END',
'P_END',
'$start',
'document',
'dummy_section',
'sections',
'doc_start',
'items',
'section',
'section_body',
'headline',
'sitems',
'sitem',
'textlines',
'block',
'table',
'lists',
'whitelines',
'variable',
'item',
'textline',
'html_quote',
'unordered_list',
'ordered_list',
'description_list',
'examples',
'example',
'list_items',
'list_item',
'table_rows',
'table_sep',
'table_row']

Racc_debug_parser = false

##### racc system variables end #####

 # reduce 0 omitted

 # reduce 1 omitted

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 15
  def _reduce_2( val, _values, result )
 result.add val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 17
  def _reduce_3( val, _values, result )
 result.add val[1]
   result
  end
.,.,

 # reduce 4 omitted

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 20
  def _reduce_5( val, _values, result )
 result = RootNode.new(val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 22
  def _reduce_6( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 23
  def _reduce_7( val, _values, result )
 result = val
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 30
  def _reduce_8( val, _values, result )
              headline = val[0][0]
              val[0].shift
              result = SectionNode.new(headline, val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 31
  def _reduce_9( val, _values, result )
 result = val
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 32
  def _reduce_10( val, _values, result )
 result = [val[0]] + val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 34
  def _reduce_11( val, _values, result )
 result = HeadlineNode.new(line_parse(val[0][1]), val[0][0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 36
  def _reduce_12( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 37
  def _reduce_13( val, _values, result )
 result = val
   result
  end
.,.,

 # reduce 14 omitted

 # reduce 15 omitted

 # reduce 16 omitted

 # reduce 17 omitted

 # reduce 18 omitted

 # reduce 19 omitted

 # reduce 20 omitted

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 47
  def _reduce_21( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 48
  def _reduce_22( val, _values, result )
 result = val
   result
  end
.,.,

 # reduce 23 omitted

 # reduce 24 omitted

 # reduce 25 omitted

 # reduce 26 omitted

 # reduce 27 omitted

 # reduce 28 omitted

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 57
  def _reduce_29( val, _values, result )
 result = VarNode.new(val[0][0], val[0][1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 59
  def _reduce_30( val, _values, result )
 result.increment
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 60
  def _reduce_31( val, _values, result )
 result = WhitelineNode.new
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 62
  def _reduce_32( val, _values, result )
 result.children << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 63
  def _reduce_33( val, _values, result )
 result = Node.new(:TEXTBLOCK, val, val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 65
  def _reduce_34( val, _values, result )
 result = TextlineNode.new(line_parse(val[0][0]), val[0])
   result
  end
.,.,

 # reduce 35 omitted

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 68
  def _reduce_36( val, _values, result )
 result = Node.new(:QUOTE, [], val[0])
   result
  end
.,.,

 # reduce 37 omitted

 # reduce 38 omitted

 # reduce 39 omitted

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 74
  def _reduce_40( val, _values, result )
 result = BlockNode.new(val[0], val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 79
  def _reduce_41( val, _values, result )
              params = ["EXAMPLE", val[0][0].value, val[0][0].indent]
	      result = BlockNode.new(params, val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 80
  def _reduce_42( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 81
  def _reduce_43( val, _values, result )
 result = val
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 83
  def _reduce_44( val, _values, result )
 result = TextlineNode.new(line_parse(val[0][0]), val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 86
  def _reduce_45( val, _values, result )
 result = Node.new(:UNORDERED_LIST, val[1], 'dummy')
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 88
  def _reduce_46( val, _values, result )
 result = Node.new(:ORDERED_LIST, val[1], 'dummy')
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 90
  def _reduce_47( val, _values, result )
 result = Node.new(:DEFINITION_LIST, val[1], 'dummy')
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 92
  def _reduce_48( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 93
  def _reduce_49( val, _values, result )
 result = val
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 99
  def _reduce_50( val, _values, result )
                result = ListitemNode.new(val[0][0], val[1], line_parse(val[0][1]), 
                                          line_parse(val[0][2]))
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 103
  def _reduce_51( val, _values, result )
	        result = ListitemNode.new(val[0][0],     [], line_parse(val[0][1]), 
		                          line_parse(val[0][2]))
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 105
  def _reduce_52( val, _values, result )
 result = TableNode.new(val[0], val[2])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 107
  def _reduce_53( val, _values, result )
 result = TableNode.new([], val[0])
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 109
  def _reduce_54( val, _values, result )
 result << val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 110
  def _reduce_55( val, _values, result )
 result = val
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 112
  def _reduce_56( val, _values, result )
 result = Node.new(:TABLE_SEP)
   result
  end
.,.,

module_eval <<'.,.,', 'lib/org-parse/struct-parser.ry', 114
  def _reduce_57( val, _values, result )
 result = TableRowNode.new(val[0])
   result
  end
.,.,

 def _reduce_none( val, _values, result )
  result
 end

  end   # class StructParser

end   # module OrgParse
